language: perl
perl:
#  - "5.10"
#  - "5.12"
#  - "5.14"
#  - "5.16"
#  - "5.18"
#  - "5.19.2"

before_install:
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
      sudo apt-get install  $( < install_misc/debian.packages)
#    - sudo apt-get install aptitude

install:
    - bash -x ./install-cpan-deps.sh

script: perl ./t/Perl.t
