<ul id="navigation">
 <li> <a href="/cgi-bin/koha/cataloguing/addbiblio.pl?biblionumber=[% biblionumber %]">Modifier notice bibliographique</a></li>
 <li> <a href="/cgi-bin/koha/catalogue/detail.pl?biblionumber=[% biblionumber %]">Vue normale</a></li>
 <li> <a href="/cgi-bin/koha/catalogue/MARCdetail.pl?biblionumber=[% biblionumber %]">Vue MARC</a></li>
 <li> <a href="/cgi-bin/koha/catalogue/ISBDdetail.pl?biblionumber=[% biblionumber %]">Vue ISBD</a></li>
</ul>