<div id="navmenu"><ul id="navmenulist">
 <li><a href="/cgi-bin/koha/labels/label-home.pl">Etiquettes</a></li>
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=layout">Gérer les formats</a></li>
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=template">Gérer les modèles</a></li>
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=profile">Gérer les profils</a></li>
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=batch">Gérer les lots de traitement</a></li>
</ul>
</div>
